version: 2.1

jobs:
  lint:
    docker:
      - image: clojure:temurin-25-lein-alpine
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-lein-deps-{{ checksum "project.clj" }}
            - v1-lein-deps-

      - run:
          name: Run linter
          command: lein check && lein eastwood

      - save_cache:
          key: v1-lein-deps-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

  unit-test:
    docker:
      - image: clojure:temurin-25-lein-alpine
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-lein-deps-{{ checksum "project.clj" }}
            - v1-lein-deps-

      - run:
          name: Run unit tests
          command: lein test :unit

      - save_cache:
          key: v1-lein-deps-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

  e2e-test:
    docker:
      - image: clojure:temurin-25-lein-alpine
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-lein-deps-{{ checksum "project.clj" }}
            - v1-lein-deps-

      - run:
          name: Run e2e tests
          command: lein test :e2e

      - save_cache:
          key: v1-lein-deps-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

  build:
    docker:
      - image: clojure:temurin-25-lein-alpine
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-lein-deps-{{ checksum "project.clj" }}
            - v1-lein-deps-

      - run:
          name: Build uberjar
          command: lein uberjar

      - save_cache:
          key: v1-lein-deps-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - persist_to_workspace:
          root: .
          paths:
            - target/uberjar/pronouns-standalone.jar

workflows:
  test-workflow:
    jobs:
      - lint
      - unit-test
      - e2e-test
      - build:
          requires:
            - lint
            - unit-test
            - e2e-test
